{{ if eq .chezmoi.os "windows" }}
["AppData/Local/nvim"]
{{ else }}
[".config/nvim"]
{{ end }}
type = "git-repo"
url = "https://github.com/BeastWalnut/nvimrc.git"

[".premake/ecc"]
type = "git-repo"
url = "https://github.com/MattBystrin/premake-ecc.git"
